export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_CANCEL = "LOGIN_USER_CANCEL";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_CANCEL = "GET_USER_CANCEL";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_CANCEL = "LOGOUT_USER_CANCEL";

export const REGISTER_USER_VALIDATION = "REGISTER_USER_VALIDATION";
export const REGISTER_USER_VALIDATION_SUCCESS = "REGISTER_USER_VALIDATION_SUCCESS";
export const REGISTER_USER_VALIDATION_CANCEL = "REGISTER_USER_VALIADTION_CANCEL";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_CANCEL = "REGISTER_USER_CANCEL";
