deployment:
  annotations: 
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: traefik


ingressRoute:
  dashboard:
    enabled: true
    annotations: { traefik.ingress.kubernetes.io/router.tls: "true" }

ports:
  web:
    redirectTo: websecure

additionalArguments:
  - "--log.level=INFO"
  - "--entrypoints.websecure.http.tls"
  - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  - "--ping"
  - "--metrics.prometheus"