server:
  service:
    enabled: true

  ha:
    enabled: true
    replicas: 1
    annotations:
      "consul.hashicorp.com/connect-inject": "true"
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }
      
      service_registration "kubernetes" {}
