basePath: /
consumes:
- application/json
- application/x-www-form-urlencoded
definitions:
  UserDTO:
    description: UserDTO is the data transfer object of the internal user object
    properties:
      birthdate:
        description: The unix birthdate of the user
        format: int64
        type: integer
        x-go-name: Birthdate
      created_at:
        description: The registration time of the user
        format: date-time
        type: string
        x-go-name: CreatedAt
      email:
        description: The email of the user
        format: email
        maxLength: 100
        minLength: 4
        type: string
        x-go-name: Email
      fullName:
        description: The full name of the user
        maxLength: 100
        minLength: 1
        type: string
        x-go-name: FullName
      id:
        description: The user id
        type: string
        x-go-name: ID
      updated_at:
        description: The time when the user was updated last
        format: date-time
        type: string
        x-go-name: UpdatedAt
      username:
        description: The username of the user
        maxLength: 100
        minLength: 4
        type: string
        x-go-name: Username
    required:
    - id
    - username
    - email
    - fullName
    - birthdate
    type: object
    x-go-package: github.com/JohnnyS318/RoyalAfgInGo/services/auth/pkg/dto
host: github.com/JohnnyS318/RoyalAfgInGo.games
info:
  contact:
    email: jonas.max.schneider@gmail.com
  description: Documentation for github.com/JohnnyS318/RoyalAfgInGo API
  license:
    name: MIT
    url: http://opensource.org/license/MIT
  title: github.com/JohnnyS318/RoyalAfgInGo API
  version: 0.0.1
paths:
  /account:
    get:
      description: return the authenticated user based on the api key
      operationId: getUser
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "401":
          $ref: '#/responses/ErrorResponse'
        "404":
          $ref: '#/responses/ErrorResponse'
        "500":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      security:
      - api_key: []
      tags:
      - account
  /account/logout:
    post:
      description: This will remove the identity cookie
      operationId: logoutUser
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/NoContentResponse'
        "401":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      security:
      - api_key: []
      summary: Logout of account
      tags:
      - account
  /account/register:
    post:
      consumes:
      - application/json
      description: This will register a new user with the provided details
      operationId: registerUser
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/ErrorResponse'
        "422":
          $ref: '#/responses/ValidationErrorResponse'
        "500":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      summary: Register a new user
      tags:
      - authentication
  /account/verify:
    get:
      description: This will return either status code 401 Unauthorized if user is
        not signed in and 200 when the login token is valid
      operationId: verifyLoggedIn
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/NoContentResponse'
        "401":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      summary: Verify that the user is logged in
      tags:
      - authentication
      - account
  /api/auth/login:
    post:
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      description: After matching credentials, this will generate a jwt and pass it
        on as a cookie
      operationId: loginUser
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "400":
          $ref: '#/responses/ErrorResponse'
        "401":
          $ref: '#/responses/ErrorResponse'
        "404":
          $ref: '#/responses/ErrorResponse'
        "422":
          $ref: '#/responses/ValidationErrorResponse'
        "500":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      summary: Login to a user account
      tags:
      - authentication
  /api/auth/session:
    get:
      description: After verification the extended jwt will be passed as a cookie
        and the user id and username will be returned
      operationId: session
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/UserResponse'
        "401":
          $ref: '#/responses/ErrorResponse'
        default:
          $ref: '#/responses/ErrorResponse'
      schemes:
      - http
      - https
      summary: Session verifies the session and extends the jwt token if valid.
produces:
- application/json
schemes:
- http
- https
security:
- api_key: []
securityDefinitions:
  api_key:
    in: cookie
    name: identity
    type: apiKey
swagger: "2.0"
