// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUserServiceServer is an autogenerated mock type for the UnsafeUserServiceServer type
type UnsafeUserServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUserServiceServer provides a mock function with given fields:
func (_m *UnsafeUserServiceServer) mustEmbedUnimplementedUserServiceServer() {
	_m.Called()
}
