apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: royalafg-web
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: royalafg-web
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: royalafg-webtls
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: royalafg-web
          port: 8080
  tls:
    certResolver: myresolver
---
apiVersion: v1
kind: Service
metadata:
  name: royalafg-web
spec:
  selector:
    app: royalafg-web
  ports:
    - name: web
      port: 8080
      targetPort: 3000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-web
data:
  .env: |
    NEXT_PUBLIC_AUTH_HOST: http://127.0.0.1:59683
    NEXT_PUBLIC_POKER_TICKET_HOST: http://127.0.0.1:59683
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-web
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "royalafg-poker-matchmaker:59683"
      labels:
        app: royalafg-web
        service: web
    spec:
      serviceAccountName: royalafg-web
      containers:
        - name: royalafg-web
          image: docker.io/johnnys318/royalafg_web:latest
          ports:
            - protocol: TCP
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_AUTH_HOST
              value: http://127.0.0.1:59683
            - name: NEXT_PUBLIC_POKER_TICKET_HOST
              value: http://127.0.0.1:59683
            - name: POKER_INFO_HOST
              value: http://127.0.0.1:59683
