apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: royalafg-auth
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api/auth`)
      kind: Rule
      services:
        - name: royalafg-auth
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: royalafg-auth
spec:
  selector:
    app: royalafg-auth
  ports:
    - name: web
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: royalafg-auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: royalafg-auth
data:
  config.yaml: |
    jwt_signing_key: testsecret
    userservice_url: localhost:5200
    cors_enabled: false
    rabbitmq_url: royalafg-rabbitmq.default.svc.cluster.local:5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: royalafg-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: royalafg-auth
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "royalafg-user:5200"
        "vault.hashicorp.com/agent-inject": "true"
        "vault.hashicorp.com/agent-inject-secret-rabbitmq.yaml": "rabbitmq/creds/royalafg"
        "vault.hashicorp.com/agent-inject-template-rabbitmq.yaml": |
          {{- with secret "rabbitmq/creds/royalafg" -}}
          rabbitmq_username: {{.Data.username}}
          rabbitmq_password: {{.Data.password}}
          {{- end }}
        "vault.hashicorp.com/agent-inject-secret-session.yaml": "kv-v2/session-secret"
        "vault.hashicorp.com/agent-inject-template-session.yaml": |
          {{- with secret "kv-v2/session-secret" -}}
          jwt_signing_key: {{.Data.data.secret}}
          {{- end }}
        "vault.hashicorp.com/role": auth-role
      labels:
        app: royalafg-auth
        service: auth
    spec:
      serviceAccountName: royalafg-auth
      containers:
        - name: royalafg-auth
          image: docker.io/johnnys318/royalafg_auth:latest
          env:
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "99"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: info
            # - name: AUTH_RABBITMQ_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       key: password
            #       name: royalafg-rabbitmq-default-user
            # - name: AUTH_RABBITMQ_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       key: username
            #       name: royalafg-rabbitmq-default-user
          resources:
              requests:
                memory: 10Mi
                cpu: 50m
              limits:
                memory: 100Mi
                cpu: 150m
          ports:
            - protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: royalafg-auth-config
              mountPath: "/etc/royalafg-auth"
      volumes:
        - name: royalafg-auth-config
          configMap:
            name: royalafg-auth
