// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// CommandHandler is an autogenerated mock type for the CommandHandler type
type CommandHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *CommandHandler) Handle(_a0 *amqp.Delivery) {
	_m.Called(_a0)
}
