// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// CommandHandler is an autogenerated mock type for the CommandHandler type
type CommandHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *CommandHandler) Handle(_a0 *amqp.Delivery) {
	_m.Called(_a0)
}

// NewCommandHandler creates a new instance of CommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandHandler {
	mock := &CommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
