// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "github.com/JohnnyS318/RoyalAfgInGo/services/search/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// GameSearch is an autogenerated mock type for the GameSearch type
type GameSearch struct {
	mock.Mock
}

// SearchGames provides a mock function with given fields: query
func (_m *GameSearch) SearchGames(query string) []dto.GameResult {
	ret := _m.Called(query)

	var r0 []dto.GameResult
	if rf, ok := ret.Get(0).(func(string) []dto.GameResult); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GameResult)
		}
	}

	return r0
}
